git:
  user_name: Alexey Immoreev
  email: lexx92@mail.ru
  diff_image_location: ~/git/open-source/git-diff-image
  ignore_file: ~/.gitignore_global
  attributes_file: ~/.gitattributes
  dir: ~/git/
iterm:
  tools_dir: ~/.iterm2
ohmyzsh:
  location: $HOME/.oh-my-zsh
ssh:
  identity: "id_ed25519"
  bw_key: "ED25519 SSH key macbook"
  bw_field: "Private key"
gpg:
  owner_email: lexx92@mail.ru
  bw_key: "GPG ECDSA key MacOS"
laptop:
  bw_key: "Laptop (MacOS)"
screenshots:
  dir: "~/Desktop/screenshots"
restic:
  job_name: "me.luixo.backup_notify"
  password:
    keychain_id: "restic_backup_password"
    bw_key: "Backrest"
    key_id: "Backup password"
  ya_s3:
    keychain_id: "yandex_s3_key"
    bw_key: "Yandex"
    key_id: "S3 key id"
    access_key: "S3 access key"
  swc_s3:
    keychain_id: "scaleway_s3_key"
    bw_key: "Scaleway"
    key_id: "S3 key id"
    access_key: "S3 access key"
