---
- name: Configure host.
  hosts: localhost

  vars:
    downloads: ~/.ansible-downloads/
  vars_files:
    - vault.yml

  pre_tasks:
    - name: Setup Bitwarden
      import_tasks: tasks/bitwarden.yml
      tags: ["always"]
    - name: Include Python dependency task
      import_tasks: tasks/python_deps.yml

  roles:
    - role: macos
      tags: ["macos"]
    - role: apps
      tags: ["apps"]
