---
- name: Verify Bitwarden CLI is present
  shell: bw --version
  changed_when: false

- name: Ensure Bitwarden is logged in
  shell: bw login --check
  register: bw_login_status
  failed_when: bw_login_status.rc != 0
  changed_when: "'You are logged in' not in bw_login_status.stdout"

- name: Unlock Bitwarden vault
  shell: bw unlock --raw "{{ bw_master_password.user_input }}"
  register: bw_unlock
  no_log: true
  changed_when: false

- name: Report error on unlocking bitwarden vault
  debug:
    msg: "Error on unlocking BW: {{ bw_unlock.stderr }}"
  when: bw_unlock.rc != 0

- name: Set Bitwarden session environment variable
  set_fact:
    bw_session: "{{ bw_unlock.stdout }}"
  when: bw_unlock.rc == 0
