# https://browniebroke.com/blog/enabling-sudo-via-touchid-using-ansible/
# https://apple.stackexchange.com/a/355880
# https://github.com/fabianishere/pam_reattach
- name: Uncomment pam_tid auth line
  become: true
  lineinfile:
    path: /etc/pam.d/sudo_local.template
    regexp: "pam_tid.so"
    line: "auth       sufficient     pam_tid.so"

- name: Add pam_reattach auth line
  become: true
  lineinfile:
    path: /etc/pam.d/sudo_local.template
    regexp: "pam_reattach.so"
    line: "auth       optional       /opt/homebrew/lib/pam/pam_reattach.so"
