---
- name: Tap priority Homebrew repos
  community.general.homebrew_tap:
    name: "{{ item }}"
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  loop:
    - gromgit/fuse

- name: Install priority Homebrew apps
  community.general.homebrew_cask:
    name: "{{ item }}"
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  loop:
    - macfuse
