---
- name: Install priority Homebrew apps
  shell: brew bundle --file=roles/macos/files/priority.bundle
  register: brew_diff
  changed_when: '"Installing" in brew_diff.stdout'

- name: Install priority Homebrew apps - Changed output
  debug:
    var: brew_diff.stdout
  when:
    - brew_diff.changed
    - not ansible_check_mode
  changed_when: brew_diff.changed
