- name: "Finder: disable extension change warning"
  osx_defaults:
    domain: "com.apple.finder"
    key: "FXEnableExtensionChangeWarning"
    type: bool
    value: false

- name: "Finder: show POSIX path in Finder title"
  osx_defaults:
    domain: "com.apple.finder"
    key: "FXShowPosixPathInTitle"
    type: bool
    value: true

- name: "Finder: new window target as home directory"
  osx_defaults:
    domain: "com.apple.finder"
    key: "NewWindowTarget"
    type: string
    value: "PfHm"

- name: "Finder: show desktop icons for external drives"
  osx_defaults:
    domain: "com.apple.finder"
    key: "ShowExternalHardDrivesOnDesktop"
    type: bool
    value: true

- name: "Finder: show desktop icons for removable media"
  osx_defaults:
    domain: "com.apple.finder"
    key: "ShowRemovableMediaOnDesktop"
    type: bool
    value: true

- name: "Finder: show path bar"
  osx_defaults:
    domain: "com.apple.finder"
    key: "ShowPathbar"
    type: bool
    value: true

- name: "Finder: show status bar"
  osx_defaults:
    domain: "com.apple.finder"
    key: "ShowStatusBar"
    type: bool
    value: true

- name: "Finder: hide recent tags from sidebar"
  osx_defaults:
    domain: "com.apple.finder"
    key: "ShowRecentTags"
    type: bool
    value: false

- name: "Finder: show all extensions"
  osx_defaults:
    domain: "NSGlobalDomain"
    key: "AppleShowAllExtensions"
    type: bool
    value: true

- name: "Finder: show all files"
  osx_defaults:
    domain: "com.apple.Finder"
    key: "AppleShowAllFiles"
    type: bool
    value: true

# TODO: migrate to osx_defaults when it supports dictionaries
# https://github.com/ansible-collections/community.general/issues/238
- name: "Finder: snap to grid"
  shell: >-
    /usr/libexec/PlistBuddy -c "{{ item }}" ~/Library/Preferences/com.apple.Finder.plist
  loop:
    - "Set :StandardViewSettings:IconViewSettings:arrangeBy name"
  changed_when: false

- name: "Finder: sort by name"
  osx_defaults:
    domain: "com.apple.Finder"
    key: "FXPreferredGroupBy"
    type: string
    value: "Name"
