- name: "Keyboard: wait interval before starting to repeat the key"
  osx_defaults:
    domain: "NSGlobalDomain"
    key: "InitialKeyRepeat"
    type: int
    value: 25

- name: "Keyboard: repeat key interval"
  osx_defaults:
    domain: "NSGlobalDomain"
    key: "KeyRepeat"
    type: int
    value: 5

- name: "Keyboard: holding a key should repeat a key"
  osx_defaults:
    domain: "NSGlobalDomain"
    key: "ApplePressAndHoldEnabled"
    state: absent

- name: "Keyboard: don't add period with double space"
  osx_defaults:
    domain: "NSGlobalDomain"
    key: "NSAutomaticPeriodSubstitutionEnabled"
    type: bool
    value: false

- name: "Keyboard: add 'next input source' hotkey"
  shell: >-
    /usr/libexec/PlistBuddy -c "{{ item }}" ~/Library/Preferences/com.apple.symbolichotkeys.plist
  loop:
    - "Set :AppleSymbolicHotKeys:60:value:parameters:2 1048576"
  changed_when: false

- name: "Keyboard: add 'previous input source' hotkey"
  shell: >-
    /usr/libexec/PlistBuddy -c "{{ item }}" ~/Library/Preferences/com.apple.symbolichotkeys.plist
  loop:
    - "Set :AppleSymbolicHotKeys:61:value:parameters:2 1572864"
  changed_when: false

- name: "Keyboard: disable 'open spotlight' hotkey"
  shell: >-
    /usr/libexec/PlistBuddy -c "{{ item }}" ~/Library/Preferences/com.apple.symbolichotkeys.plist
  loop:
    - "Set :AppleSymbolicHotKeys:64:enabled 0"
  changed_when: false

- name: "Keyboard: disable 'open finder' hotkey"
  shell: >-
    /usr/libexec/PlistBuddy -c "{{ item }}" ~/Library/Preferences/com.apple.symbolichotkeys.plist
  loop:
    - "Set :AppleSymbolicHotKeys:65:enabled 0"
  changed_when: false

# TODO: Uncomment this and remove a few previous tasks when we can put proper values in dicts
# https://github.com/ansible-collections/community.general/issues/238#issuecomment-4126880219
# - name: "Keyboard: hotkeys"
#   osx_defaults:
#     domain: "com.apple.symbolichotkeys"
#     key: "AppleSymbolicHotKeys"
#     type: dict
#     dict_mode: add
#     value:
#       # add 'next input source' hotkey
#       60:
#         value:
#           parameters: [32, 49, 1048576]
#       # add 'previous input source' hotkey
#       61:
#         value:
#           parameters: [32, 49, 1572864]
#       # disable 'open spotlight' hotkey
#       64:
#         value:
#           enabled: false
#       # disable 'open finder' hotkey
#       65:
#         value:
#           enabled: false

- name: "Keyboard: remove all keyboards"
  shell: >-
    /usr/libexec/PlistBuddy -c "{{ item }}" ~/Library/Preferences/com.apple.HIToolbox.plist
  loop:
    - "Delete :AppleEnabledInputSources"
    - "Add :AppleEnabledInputSources array"
    - "Add :AppleEnabledInputSources: dict"
    - "Add :AppleEnabledInputSources:0:InputSourceKind string 'Keyboard Layout'"
    - "Add :AppleEnabledInputSources:0:'KeyboardLayout ID' integer 252"
    - "Add :AppleEnabledInputSources:0:'KeyboardLayout Name' string ABC"
    - "Add :AppleEnabledInputSources: dict"
    - "Add :AppleEnabledInputSources:1:InputSourceKind string 'Keyboard Layout'"
    - "Add :AppleEnabledInputSources:1:'KeyboardLayout ID' integer 19458"
    - "Add :AppleEnabledInputSources:1:'KeyboardLayout Name' string RussianWin"
  changed_when: false

# TODO: Uncomment this and remove a few previous tasks when we can put proper values in dicts
# https://github.com/ansible-collections/community.general/issues/238#issuecomment-4126880219
# - name: "Keyboard: remove all keyboards"
#   osx_defaults:
#     domain: "com.apple.HIToolbox"
#     key: "AppleEnabledInputSources"
#     type: array
#     value:
#       - InputSourceKind: "Keyboard Layout"
#         "KeyboardLayout ID": 252
#         "KeyboardLayout Name": "ABC"
#       - InputSourceKind: "Keyboard Layout"
#         "KeyboardLayout ID": 19458
#         "KeyboardLayout Name": "RussianWin"

- name: "Keyboard: use globe key to show emoji panel"
  osx_defaults:
    domain: "com.apple.HIToolbox"
    key: "AppleFnUsageType"
    type: int
    value: 2

- name: "Keyboard: turn off the language indicator while switching input sources."
  osx_defaults:
    domain: "kCFPreferencesAnyApplication"
    key: "TSMLanguageIndicatorEnabled"
    type: bool
    value: false
