---
- name: Add backup keys to keychain
  vars:
    laptop_password: "{{ lookup('community.general.bitwarden', laptop.bw_key, field='password', bw_session=bw_session)[0] }}"
  block:
    - name: Store backup password
      community.general.keyring:
        keyring_password: "{{ laptop_password }}"
        service: "{{ restic.password.keychain_id }}"
        username: restic
        password: "{{ lookup('community.general.bitwarden', restic.password.bw_key, field=restic.password.key_id, bw_session=bw_session)[0] }}"
