---
- name: Verify iterm tools dir exists
  ansible.builtin.file:
    path: "{{ iterm.tools_dir }}"
    state: directory
    mode: 0755

- name: Download iterm utilities to show images
  ansible.builtin.get_url:
    url: https://iterm2.com/utilities/{{ item }}
    dest: "{{ iterm.tools_dir }}/{{ item }}"
    mode: 0755
  loop:
    - imgls
    - imgcat

- name: Download shell integration script
  ansible.builtin.get_url:
    url: https://iterm2.com/shell_integration/zsh
    dest: "{{ iterm.tools_dir }}/.iterm2_shell_integration.zsh"
    mode: 0755

- name: Add shell integration script to the run
  ansible.builtin.blockinfile:
    path: "~/.zshrc"
    marker: "# {mark} Shell integration"
    append_newline: true
    prepend_newline: true
    block: |
      source {{ iterm.tools_dir }}/.iterm2_shell_integration.zsh

- name: "Defaults: set load settings from custom file"
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/Falkor/dotfiles/raw/refs/heads/master/fonts/SourceCodePro+Powerline+Awesome+Regular.ttf"
    dest: /Library/Fonts/

- name: "Defaults: add dynamic profiles list"
  block:
    - name: "Ensures directory exists"
      file:
        path: "~/Library/Application Support/iTerm2/DynamicProfiles"
        recurse: true
        state: directory

    - name: "Copy over the profiles"
      ansible.builtin.copy:
        src: "{{ role_path }}/files/{{ item }}"
        dest: "~/Library/Application Support/iTerm2/DynamicProfiles"
        mode: 0644
      loop:
        - Profiles.json
