---
- name: Verify iterm tools dir exists
  ansible.builtin.file:
    path: "{{ iterm.tools_dir }}"
    state: directory
    mode: 0755

- name: Download iterm utilities to show images
  ansible.builtin.get_url:
    url: https://iterm2.com/utilities/{{ item }}
    dest: "{{ iterm.tools_dir }}/{{ item }}"
    mode: 0755
  loop:
    - imgls
    - imgcat

- name: Download shell integration script
  ansible.builtin.get_url:
    url: https://iterm2.com/shell_integration/zsh
    dest: "{{ iterm.tools_dir }}/.iterm2_shell_integration.zsh"
    mode: 0755

- name: Add shell integration script to the run
  ansible.builtin.blockinfile:
    path: "~/.zshrc"
    marker: "# {mark} Shell integration"
    append_newline: true
    prepend_newline: true
    block: |
      source {{ iterm.tools_dir }}/.iterm2_shell_integration.zsh

- name: "Defaults: set custom file to load settings from"
  osx_defaults:
    domain: "com.googlecode.iterm2"
    key: "PrefsCustomFolder"
    type: string
    value: "~/.iterm2_settings"

- name: "Defaults: set load settings from custom file"
  osx_defaults:
    domain: "com.googlecode.iterm2"
    key: "LoadPrefsFromCustomFolder"
    type: bool
    value: true
